const collegesData = [
  {
    slug:"amity-mba", name:"Amity University Online", shortName:"Amity",
    logo:"AU", color:"#c0392b", program:"MBA",
    fees:199000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Noida, Uttar Pradesh", established:1995, ranking:"Top 10 Private Uni",
    specializations:["Marketing","Finance","HR","Operations","Business Analytics"],
    highlights:["UGC-DEB Approved","Live Weekend Classes","Dedicated Career Cell","1L+ Alumni Network"],
    placement:{ avg:"6–8 LPA", top:"18 LPA", rate:"100% Support" },
    description:"Amity University Online offers a 2-year Online MBA backed by 25+ years of academic legacy. The program features live weekend sessions, industry-aligned curriculum, and a dedicated career assistance cell that helps students with resume building, interview preparation, and job referrals.",
    eligibility:"Graduation in any discipline with min. 50% marks",
    emi:"₹8,300", students:"45,000+"
  },
  {
    slug:"nmims-mba", name:"NMIMS Global Access", shortName:"NMIMS",
    logo:"NM", color:"#2c3e7a", program:"MBA",
    fees:196000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Mumbai, Maharashtra", established:1981, ranking:"Top 8 B-School",
    specializations:["Finance","Operations","Marketing","Business Analytics","Supply Chain"],
    highlights:["AICTE Approved","Bloomberg Market Lab","500+ Hiring Partners","Industry Live Projects"],
    placement:{ avg:"7–10 LPA", top:"24 LPA", rate:"100% Support" },
    description:"NMIMS Global Access is one of India's most respected business schools. Its Online MBA is known for Finance and Analytics specializations, Bloomberg terminal access, and industry-integrated capstone projects. The career services team actively connects students with 500+ hiring companies.",
    eligibility:"Graduation with 50% marks; work experience preferred",
    emi:"₹8,167", students:"30,000+"
  },
  {
    slug:"manipal-mba", name:"Manipal University Online", shortName:"Manipal",
    logo:"MU", color:"#e67e22", program:"MBA",
    fees:292000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Manipal, Karnataka", established:1953, ranking:"Top 6 Private Uni",
    specializations:["HRM","Marketing","IT Management","Finance","Healthcare Mgmt"],
    highlights:["70-Year Legacy","Coursera Certifications Included","1000+ Campus Recruiters","24/7 LMS Access"],
    placement:{ avg:"7–12 LPA", top:"28 LPA", rate:"100% Support" },
    description:"Manipal University Online brings 70 years of academic excellence to your screen. The program uniquely integrates Coursera's global certifications into the curriculum at no extra cost. A dedicated placement team, over 1000 empanelled recruiters, and a global alumni network ensure strong career outcomes.",
    eligibility:"Graduation in any stream with 50% aggregate marks",
    emi:"₹12,167", students:"60,000+"
  },
  {
    slug:"lpu-mba", name:"LPU Online MBA", shortName:"LPU",
    logo:"LPU", color:"#8e44ad", program:"MBA",
    fees:180000, duration:"2 Years", accreditation:"NAAC A++",
    location:"Phagwara, Punjab", established:2005, ranking:"NAAC A++ (Highest)",
    specializations:["Marketing","Logistics","IT","Finance","International Business"],
    highlights:["India's Highest NAAC A++","AI-Powered Learning Platform","500+ Industry Partners","Scholarship up to 50%"],
    placement:{ avg:"6–9 LPA", top:"22 LPA", rate:"100% Support" },
    description:"LPU Online holds India's highest NAAC A++ accreditation. Its AI-powered adaptive learning platform personalizes education for each student's pace. With 500+ industry partners, regular virtual career fairs, and dedicated placement mentors, LPU ensures every student gets career support from day one.",
    eligibility:"Graduation with 45% marks; any discipline",
    emi:"₹7,500", students:"80,000+"
  },
  {
    slug:"jain-mba", name:"Jain University Online", shortName:"Jain",
    logo:"JU", color:"#27ae60", program:"MBA",
    fees:175000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Bangalore, Karnataka", established:1990, ranking:"Top 50 MBA Programs",
    specializations:["Entrepreneurship","Finance","Marketing","Digital Business"],
    highlights:["Startup Incubation Access","Google Certified Faculty","Bangalore Tech Network","Pitch Competitions & Funding"],
    placement:{ avg:"6–8 LPA", top:"18 LPA", rate:"100% Support" },
    description:"Jain University Online is the ideal choice for entrepreneurs. Based in Bangalore, India's startup capital, the MBA program gives access to incubation centers, seed funding networks, and a thriving alumni startup community. The career cell runs monthly virtual hiring events with 200+ companies.",
    eligibility:"Graduation with 50% marks in any discipline",
    emi:"₹7,292", students:"25,000+"
  },
  {
    slug:"lpu-bba", name:"LPU Online BBA", shortName:"LPU",
    logo:"LPU", color:"#8e44ad", program:"BBA",
    fees:120000, duration:"3 Years", accreditation:"NAAC A++",
    location:"Phagwara, Punjab", established:2005, ranking:"NAAC A++ (Highest)",
    specializations:["General Management","Marketing","Finance","Entrepreneurship"],
    highlights:["NAAC A++ Rated","Live Faculty Interaction","Internship Placement Help","Real Industry Projects"],
    placement:{ avg:"3.5–5 LPA", top:"12 LPA", rate:"100% Support" },
    description:"LPU Online BBA is perfect for undergraduate students wanting a quality business degree with complete flexibility. The program includes live mentorship sessions, real industry projects, and a dedicated internship cell that helps students secure internships with top companies during their course.",
    eligibility:"Class 12 (10+2) in any stream with 45% marks",
    emi:"₹3,333", students:"40,000+"
  },
  {
    slug:"cu-bba", name:"Chandigarh University BBA", shortName:"CU",
    logo:"CU", color:"#1abc9c", program:"BBA",
    fees:140000, duration:"3 Years", accreditation:"NAAC A+",
    location:"Chandigarh, Punjab", established:2012, ranking:"Top 5 Emerging Uni",
    specializations:["Business Management","Digital Marketing","Finance","HR"],
    highlights:["UGC-DEB Approved","1200+ Annual Placements","E-Library & Study Tools","Industry Webinars Monthly"],
    placement:{ avg:"3.5–5.5 LPA", top:"14 LPA", rate:"100% Support" },
    description:"Chandigarh University BBA Online combines a strong business curriculum with practical digital skills. The university's strong industry connections across North India ensure that graduates have access to a wide placement network. Monthly webinars with industry leaders keep students updated on market trends.",
    eligibility:"Class 12 (10+2) in any stream",
    emi:"₹3,889", students:"35,000+"
  },
  {
    slug:"amity-bba", name:"Amity Online BBA", shortName:"Amity",
    logo:"AU", color:"#c0392b", program:"BBA",
    fees:165000, duration:"3 Years", accreditation:"NAAC A+",
    location:"Noida, Uttar Pradesh", established:1995, ranking:"Top 10 Private Uni",
    specializations:["Marketing","Finance","International Business","HR"],
    highlights:["25-Year Brand Legacy","Harvard Case Study Method","Alumni Network of 1 Lakh+","Global Exchange Programs"],
    placement:{ avg:"3–5 LPA", top:"11 LPA", rate:"100% Support" },
    description:"Amity Online BBA brings the trusted Amity brand to your fingertips. The Harvard-style case study curriculum builds real problem-solving skills. With one of India's largest alumni networks, graduates have access to referrals and mentorship across every major industry sector.",
    eligibility:"Class 12 (10+2) with 50% marks",
    emi:"₹4,583", students:"20,000+"
  },
  {
    slug:"jain-bca", name:"Jain University BCA", shortName:"Jain",
    logo:"JU", color:"#27ae60", program:"BCA",
    fees:150000, duration:"3 Years", accreditation:"NAAC A+",
    location:"Bangalore, Karnataka", established:1990, ranking:"Top 50 Tech Programs",
    specializations:["Web Development","Data Science","Cloud Computing","Cybersecurity"],
    highlights:["Located in IT Hub Bangalore","Hackathon Culture","GitHub & Open Source Projects","Startup Mentor Access"],
    placement:{ avg:"4–6 LPA", top:"16 LPA", rate:"100% Support" },
    description:"Jain University BCA puts you at the centre of India's tech ecosystem in Bangalore. Industry experts designed the curriculum, covering web development, cloud, and data science. Students participate in hackathons, contribute to open-source projects, and get mentorship from startup founders and tech leaders.",
    eligibility:"Class 12 (10+2) with Mathematics preferred; 45% marks",
    emi:"₹4,167", students:"15,000+"
  },
  {
    slug:"amrita-bca", name:"Amrita Online BCA", shortName:"Amrita",
    logo:"AOL", color:"#e74c3c", program:"BCA",
    fees:120000, duration:"3 Years", accreditation:"NAAC A++",
    location:"Coimbatore, Tamil Nadu", established:1994, ranking:"Top 5 Tech University",
    specializations:["AI & Machine Learning","Full Stack Dev","Data Science","Mobile App Dev"],
    highlights:["NAAC A++ (Most Affordable)","Google & Microsoft Tie-ups","AI Research Labs Access","100% Digital Curriculum"],
    placement:{ avg:"4–6.5 LPA", top:"18 LPA", rate:"100% Support" },
    description:"Amrita Online BCA is one of the most affordable NAAC A++ programs in India. With dedicated AI and ML labs, Google and Microsoft academic partnerships, and a fully digital curriculum, it prepares students comprehensively for tomorrow's technology landscape. The career cell runs regular virtual campus drives.",
    eligibility:"Class 12 (10+2) in any stream with 45% marks",
    emi:"₹3,333", students:"18,000+"
  },
  {
    slug:"lpu-bca", name:"LPU Online BCA", shortName:"LPU",
    logo:"LPU", color:"#8e44ad", program:"BCA",
    fees:135000, duration:"3 Years", accreditation:"NAAC A++",
    location:"Phagwara, Punjab", established:2005, ranking:"NAAC A++ (Highest)",
    specializations:["Web Dev","App Dev","Data Analytics","Cloud & Networking"],
    highlights:["NAAC A++","Weekly Coding Bootcamps","AWS & Azure Certified Training","Live Client Project Experience"],
    placement:{ avg:"4–5.5 LPA", top:"15 LPA", rate:"100% Support" },
    description:"LPU Online BCA is celebrated for its hands-on, industry-first learning approach. Students work on live client projects, attend weekly coding bootcamps, and earn AWS and Azure cloud certifications as part of the curriculum. The dedicated tech placement cell conducts regular virtual hiring drives with 300+ IT companies.",
    eligibility:"Class 12 (10+2) in any stream",
    emi:"₹3,750", students:"22,000+"
  },
  {
    slug:"ignou-mca", name:"IGNOU MCA", shortName:"IGNOU",
    logo:"IG", color:"#2980b9", program:"MCA",
    fees:62000, duration:"2 Years", accreditation:"Central University",
    location:"New Delhi", established:1985, ranking:"India's Largest University",
    specializations:["Software Engineering","Network Security","Database Management"],
    highlights:["Government University — Most Trusted","India's Most Affordable MCA","Valid for Govt & PSU Jobs","120+ Study Centres Pan-India"],
    placement:{ avg:"4–6 LPA", top:"14 LPA", rate:"Placement Guidance" },
    description:"IGNOU MCA is the most affordable and accessible MCA program from a Central Government university. Widely accepted for government positions, PSU jobs, and higher studies abroad, it is the ideal choice for budget-conscious students who need a credible, government-backed qualification in computer applications.",
    eligibility:"BCA / B.Sc. Computer Science or Graduation with Mathematics",
    emi:"₹2,583", students:"2,00,000+"
  },
  {
    slug:"sikkim-mca", name:"Sikkim Manipal MCA", shortName:"SMU",
    logo:"SM", color:"#16a085", program:"MCA",
    fees:125000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Gangtok, Sikkim", established:1995, ranking:"Top 20 MCA Programs",
    specializations:["Cloud Computing","AI & ML","Cybersecurity","Software Development"],
    highlights:["Manipal Group Brand","TCS & Infosys Academic Partners","IBM Certified Curriculum","Hands-on Practical Labs"],
    placement:{ avg:"5–7 LPA", top:"18 LPA", rate:"100% Support" },
    description:"Sikkim Manipal University MCA combines the Manipal Group's academic reputation with industry-grade technical training. Partnerships with TCS, Infosys, and IBM ensure the curriculum stays aligned with current industry demands. The career services team facilitates virtual campus drives and placement preparation workshops.",
    eligibility:"Graduation with Mathematics/Statistics/CS with 50% marks",
    emi:"₹5,208", students:"12,000+"
  },
  {
    slug:"cu-mca", name:"Chandigarh University MCA", shortName:"CU",
    logo:"CU", color:"#1abc9c", program:"MCA",
    fees:150000, duration:"2 Years", accreditation:"NAAC A+",
    location:"Chandigarh, Punjab", established:2012, ranking:"Top 5 Emerging Uni",
    specializations:["Full Stack Development","DevOps","Data Science","Blockchain"],
    highlights:["1200+ Tech Placements/Year","National Hackathon Champions","Cloud Lab Certification","Industry Live Projects"],
    placement:{ avg:"5.5–8 LPA", top:"20 LPA", rate:"100% Support" },
    description:"Chandigarh University MCA is celebrated across the IT sector for outstanding placement results. With dedicated cloud computing labs, DevOps certification tracks, and regular participation in national hackathons, graduates are fully job-ready from day one. The tech placement cell facilitates hiring from 400+ IT companies annually.",
    eligibility:"Graduation in CS / IT / BCA or any degree with Mathematics",
    emi:"₹6,250", students:"20,000+"
  },
  {
    slug:"lpu-mca", name:"LPU Online MCA", shortName:"LPU",
    logo:"LPU", color:"#8e44ad", program:"MCA",
    fees:160000, duration:"2 Years", accreditation:"NAAC A++",
    location:"Phagwara, Punjab", established:2005, ranking:"NAAC A++ (Highest)",
    specializations:["AI Engineering","Data Science","App Development","Cybersecurity"],
    highlights:["Unique AI Engineering Specialization","500+ Hiring Partners","NAAC A++ Rated","Lateral Entry Available"],
    placement:{ avg:"6–9 LPA", top:"22 LPA", rate:"100% Support" },
    description:"LPU Online MCA is the highest-rated MCA program in India with NAAC A++ accreditation. Its exclusive AI Engineering specialization prepares students for machine learning, NLP, and AI product development roles at top tech companies. With 500+ hiring partners and a dedicated tech placement cell, career outcomes are exceptional.",
    eligibility:"BCA / B.Sc. IT / CS with 50% or any graduation with Mathematics",
    emi:"₹6,667", students:"28,000+"
  }
];
