const collegesData = [
  {
    slug: "amity-mba",
    name: "Amity University Online",
    shortName: "Amity",
    program: "MBA",
    fees: 199000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Noida, Uttar Pradesh",
    established: 1995,
    ranking: "#12 Private University",
    logo: "AU",
    color: "#c0392b",
    specializations: ["Marketing", "Finance", "HR", "Operations", "Business Analytics"],
    highlights: ["UGC-DEB Approved", "ISO 9001:2015", "Live Weekend Classes", "Industry Mentors"],
    placement: { avg: "8.5 LPA", top: "22 LPA", rate: "88%" },
    description: "Amity University Online offers a comprehensive MBA program blending academic excellence with industry relevance. With over 25 years of educational legacy, it provides cutting-edge curriculum, live faculty interaction, and robust placement support.",
    eligibility: "Graduation in any discipline with minimum 50% marks",
    emi: "₹8,300/month",
    students: "45,000+",
    website: "#"
  },
  {
    slug: "nmims-mba",
    name: "NMIMS Global Access",
    shortName: "NMIMS",
    program: "MBA",
    fees: 196000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Mumbai, Maharashtra",
    established: 1981,
    ranking: "#8 Management School",
    logo: "NM",
    color: "#2c3e7a",
    specializations: ["Finance", "Operations", "Marketing", "Business Analytics", "Supply Chain"],
    highlights: ["AICTE Approved", "Live Sessions", "Bloomberg Terminal Access", "Global Alumni Network"],
    placement: { avg: "9.2 LPA", top: "28 LPA", rate: "91%" },
    description: "NMIMS Global Access School for Continuing Education is one of India's most respected MBA institutions. Known for finance and analytics specializations, it offers world-class curriculum with Bloomberg market simulations and industry-integrated projects.",
    eligibility: "Graduation with 50% marks; work experience preferred",
    emi: "₹8,167/month",
    students: "30,000+",
    website: "#"
  },
  {
    slug: "manipal-mba",
    name: "Manipal University Online",
    shortName: "Manipal",
    program: "MBA",
    fees: 292000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Manipal, Karnataka",
    established: 1953,
    ranking: "#6 Private University",
    logo: "MU",
    color: "#e67e22",
    specializations: ["HRM", "Marketing", "IT Management", "Finance", "Healthcare"],
    highlights: ["70 Year Legacy", "Coursera Integration", "1000+ Recruiters", "24/7 LMS Access"],
    placement: { avg: "9.8 LPA", top: "32 LPA", rate: "93%" },
    description: "Manipal University Online leverages 70 years of academic excellence to deliver a premium online MBA experience. Its unique Coursera integration gives students access to global certifications embedded within the curriculum.",
    eligibility: "Graduation in any stream with 50% aggregate marks",
    emi: "₹12,167/month",
    students: "60,000+",
    website: "#"
  },
  {
    slug: "lpu-mba",
    name: "LPU Online MBA",
    shortName: "LPU",
    program: "MBA",
    fees: 180000,
    duration: "2 Years",
    accreditation: "NAAC A++",
    location: "Phagwara, Punjab",
    established: 2005,
    ranking: "#3 Innovative University",
    logo: "LPU",
    color: "#8e44ad",
    specializations: ["Marketing", "Logistics", "IT", "Finance", "International Business"],
    highlights: ["NAAC A++ (Highest)", "AI-Powered Learning", "500+ Industry Partners", "Scholarship Available"],
    placement: { avg: "8.8 LPA", top: "25 LPA", rate: "90%" },
    description: "LPU Online holds India's highest NAAC A++ accreditation, making it the top-rated online university in the country. Its AI-powered adaptive learning platform personalizes education for each student's pace and learning style.",
    eligibility: "Graduation with 45% marks; any discipline",
    emi: "₹7,500/month",
    students: "80,000+",
    website: "#"
  },
  {
    slug: "jain-mba",
    name: "Jain University Online",
    shortName: "Jain",
    program: "MBA",
    fees: 175000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Bangalore, Karnataka",
    established: 1990,
    ranking: "Top 50 MBA",
    logo: "JU",
    color: "#27ae60",
    specializations: ["Entrepreneurship", "Finance", "Marketing", "Digital Business"],
    highlights: ["Startup Ecosystem", "Incubation Center", "Google Certified Faculty", "Bangalore Tech Network"],
    placement: { avg: "8.2 LPA", top: "20 LPA", rate: "86%" },
    description: "Jain University Online is the go-to choice for aspiring entrepreneurs. Located in India's startup capital Bangalore, it offers a unique entrepreneurship track with access to incubation centers, seed funding networks, and a thriving alumni startup community.",
    eligibility: "Graduation with 50% marks in any discipline",
    emi: "₹7,292/month",
    students: "25,000+",
    website: "#"
  },
  {
    slug: "lpu-bba",
    name: "LPU Online BBA",
    shortName: "LPU",
    program: "BBA",
    fees: 120000,
    duration: "3 Years",
    accreditation: "NAAC A++",
    location: "Phagwara, Punjab",
    established: 2005,
    ranking: "#3 Innovative University",
    logo: "LPU",
    color: "#8e44ad",
    specializations: ["General Management", "Marketing", "Finance", "Entrepreneurship"],
    highlights: ["NAAC A++", "Live Sessions", "Internship Support", "Industry Projects"],
    placement: { avg: "4.5 LPA", top: "12 LPA", rate: "82%" },
    description: "LPU's Online BBA is perfect for students who want a quality undergraduate business degree with maximum flexibility. The program includes live mentorship, real industry projects, and dedicated internship placement support.",
    eligibility: "10+2 (Class XII) in any stream with 45% marks",
    emi: "₹3,333/month",
    students: "40,000+",
    website: "#"
  },
  {
    slug: "cu-bba",
    name: "Chandigarh University BBA",
    shortName: "CU",
    program: "BBA",
    fees: 140000,
    duration: "3 Years",
    accreditation: "NAAC A+",
    location: "Chandigarh, Punjab",
    established: 2012,
    ranking: "#5 Emerging University",
    logo: "CU",
    color: "#1abc9c",
    specializations: ["Business Management", "Digital Marketing", "Finance", "HR"],
    highlights: ["UGC Approved", "1200+ Placements", "E-Library Access", "Industry Webinars"],
    placement: { avg: "4.8 LPA", top: "14 LPA", rate: "85%" },
    description: "Chandigarh University's BBA program offers a well-rounded business education with strong placement networks across North India. Its digital-first approach ensures students are equipped with modern business and technology skills.",
    eligibility: "10+2 in any stream",
    emi: "₹3,889/month",
    students: "35,000+",
    website: "#"
  },
  {
    slug: "amity-bba",
    name: "Amity Online BBA",
    shortName: "Amity",
    program: "BBA",
    fees: 165000,
    duration: "3 Years",
    accreditation: "NAAC A+",
    location: "Noida, Uttar Pradesh",
    established: 1995,
    ranking: "#12 Private University",
    logo: "AU",
    color: "#c0392b",
    specializations: ["Marketing", "Finance", "International Business", "HR"],
    highlights: ["25 Year Legacy", "Global Exposure", "Case Study Method", "Alumni Network of 1L+"],
    placement: { avg: "4.2 LPA", top: "11 LPA", rate: "80%" },
    description: "Amity Online BBA brings the prestigious Amity brand to online learners. The program uses Harvard-style case studies and has one of the largest alumni networks in India, opening doors across industries.",
    eligibility: "10+2 with 50% marks",
    emi: "₹4,583/month",
    students: "20,000+",
    website: "#"
  },
  {
    slug: "jain-bca",
    name: "Jain University BCA",
    shortName: "Jain",
    program: "BCA",
    fees: 150000,
    duration: "3 Years",
    accreditation: "NAAC A+",
    location: "Bangalore, Karnataka",
    established: 1990,
    ranking: "Top 50 Tech Programs",
    logo: "JU",
    color: "#27ae60",
    specializations: ["Web Development", "Data Science", "Cloud Computing", "Cybersecurity"],
    highlights: ["Bangalore Tech Hub", "GitHub Certified", "Hackathon Culture", "Startup Mentors"],
    placement: { avg: "5.5 LPA", top: "16 LPA", rate: "87%" },
    description: "Jain University BCA in Bangalore puts you at the heart of India's tech ecosystem. With a curriculum designed by industry experts, students learn cutting-edge tech skills and participate in hackathons, open-source projects, and startup internships.",
    eligibility: "10+2 with Mathematics (preferred) with 45% marks",
    emi: "₹4,167/month",
    students: "15,000+",
    website: "#"
  },
  {
    slug: "amrita-bca",
    name: "Amrita Online BCA",
    shortName: "Amrita",
    program: "BCA",
    fees: 120000,
    duration: "3 Years",
    accreditation: "NAAC A++",
    location: "Coimbatore, Tamil Nadu",
    established: 1994,
    ranking: "#5 Tech University",
    logo: "AO",
    color: "#e74c3c",
    specializations: ["AI & ML", "Full Stack Dev", "Data Science", "Mobile App Dev"],
    highlights: ["NAAC A++ (Highest)", "AI Research Labs", "Google-Microsoft Tie-up", "100% Digital Curriculum"],
    placement: { avg: "5.8 LPA", top: "18 LPA", rate: "90%" },
    description: "Amrita Online BCA is one of the most affordable NAAC A++ programs in India. With dedicated AI and ML labs, Google and Microsoft collaborations, and a 100% digital curriculum, it prepares students for the jobs of tomorrow.",
    eligibility: "10+2 in any stream with 45% marks",
    emi: "₹3,333/month",
    students: "18,000+",
    website: "#"
  },
  {
    slug: "lpu-bca",
    name: "LPU Online BCA",
    shortName: "LPU",
    program: "BCA",
    fees: 135000,
    duration: "3 Years",
    accreditation: "NAAC A++",
    location: "Phagwara, Punjab",
    established: 2005,
    ranking: "#3 Innovative University",
    logo: "LPU",
    color: "#8e44ad",
    specializations: ["Web Dev", "App Dev", "Data Analytics", "Networking"],
    highlights: ["NAAC A++", "Coding Bootcamps", "Live Projects", "AWS & Azure Training"],
    placement: { avg: "5.2 LPA", top: "15 LPA", rate: "88%" },
    description: "LPU Online BCA is renowned for its practical, industry-first approach to computer applications education. Students work on live client projects, attend weekly coding bootcamps, and earn cloud computing certifications as part of the curriculum.",
    eligibility: "10+2 in any stream",
    emi: "₹3,750/month",
    students: "22,000+",
    website: "#"
  },
  {
    slug: "ignou-mca",
    name: "IGNOU MCA",
    shortName: "IGNOU",
    program: "MCA",
    fees: 62000,
    duration: "2 Years",
    accreditation: "Central University",
    location: "New Delhi",
    established: 1985,
    ranking: "India's Largest University",
    logo: "IG",
    color: "#2980b9",
    specializations: ["Software Engineering", "Network Security", "Data Management"],
    highlights: ["Government University", "Most Affordable MCA", "120 Study Centers", "Valid for Govt Jobs"],
    placement: { avg: "5.0 LPA", top: "14 LPA", rate: "75%" },
    description: "IGNOU MCA is the most affordable and accessible MCA program in India from a Central Government university. Widely accepted for government positions, PSU jobs, and higher studies, it's the ideal choice for budget-conscious learners.",
    eligibility: "BCA/B.Sc. Computer Science or graduation with Mathematics",
    emi: "₹2,583/month",
    students: "2,00,000+",
    website: "#"
  },
  {
    slug: "sikkim-mca",
    name: "Sikkim Manipal MCA",
    shortName: "SMU",
    program: "MCA",
    fees: 125000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Gangtok, Sikkim",
    established: 1995,
    ranking: "Top 20 MCA Programs",
    logo: "SM",
    color: "#16a085",
    specializations: ["Cloud Computing", "AI & ML", "Cybersecurity", "Software Development"],
    highlights: ["Manipal Group", "TCS & Infosys Partners", "IBM Certified Curriculum", "Practical Labs"],
    placement: { avg: "6.2 LPA", top: "18 LPA", rate: "85%" },
    description: "Sikkim Manipal University's MCA program combines the Manipal Group's academic legacy with industry-grade technical training. Partnership with TCS, Infosys, and IBM ensures the curriculum is always aligned with industry demands.",
    eligibility: "Graduation with Mathematics/Statistics/Computer Science with 50%",
    emi: "₹5,208/month",
    students: "12,000+",
    website: "#"
  },
  {
    slug: "cu-mca",
    name: "Chandigarh University MCA",
    shortName: "CU",
    program: "MCA",
    fees: 150000,
    duration: "2 Years",
    accreditation: "NAAC A+",
    location: "Chandigarh, Punjab",
    established: 2012,
    ranking: "#5 Emerging University",
    logo: "CU",
    color: "#1abc9c",
    specializations: ["Full Stack Dev", "DevOps", "Data Science", "Blockchain"],
    highlights: ["1200+ Tech Placements", "Hackathon Winners", "Industry Projects", "Cloud Labs"],
    placement: { avg: "6.8 LPA", top: "20 LPA", rate: "88%" },
    description: "CU's MCA program is celebrated for its strong placement record in the IT sector. With dedicated cloud computing labs, DevOps certification tracks, and participation in national hackathons, graduates are ready for top tech roles from day one.",
    eligibility: "Graduation in CS/IT/BCA or any degree with Math",
    emi: "₹6,250/month",
    students: "20,000+",
    website: "#"
  },
  {
    slug: "lpu-mca",
    name: "LPU Online MCA",
    shortName: "LPU",
    program: "MCA",
    fees: 160000,
    duration: "2 Years",
    accreditation: "NAAC A++",
    location: "Phagwara, Punjab",
    established: 2005,
    ranking: "#3 Innovative University",
    logo: "LPU",
    color: "#8e44ad",
    specializations: ["AI Engineering", "Data Science", "App Development", "Cybersecurity"],
    highlights: ["NAAC A++ (Highest)", "AI Specialization", "500+ Hiring Partners", "Lateral Entry Available"],
    placement: { avg: "7.0 LPA", top: "22 LPA", rate: "91%" },
    description: "LPU Online MCA is the highest-rated MCA program in India. Its AI Engineering specialization is unique in the country, preparing students for roles in machine learning, NLP, and AI product development at top tech companies.",
    eligibility: "BCA/B.Sc. IT/CS with 50% or any graduation with Math",
    emi: "₹6,667/month",
    students: "28,000+",
    website: "#"
  }
];
